alter table Attachment drop foreign key FKd5xpm81gxg8n40167lbu5rbfb;
alter table Attachment drop foreign key FKjj9psk52ifamilliyo16epwpc;
alter table BooleanExpression drop foreign key FKqth56a8k6d8pv6ngsu2vjp4kj;
alter table CorrelationPropertyInfo drop foreign key FKbchyl7kb8i6ghvi3dbr86bgo0;
alter table Deadline drop foreign key FK361ggw230po88svgfasg36i2w;
alter table Deadline drop foreign key FKpeiadnoy228t35213t63c3imm;
alter table Delegation_delegates drop foreign key FKewkdyi0wrgy9byp6abyglpcxq;
alter table Delegation_delegates drop foreign key FK85x3trafk3wfbrv719cafr591;
alter table ErrorInfo drop foreign key FKdarp6ushq06q39jmij3fdpdbs;
alter table Escalation drop foreign key FK37v8ova8ti6jiblda7n6j298e;
alter table I18NText drop foreign key FKcd6eb4q62d9ab8p0di8pb99ch;
alter table I18NText drop foreign key FKiogka67sji8fk4cp7a369895i;
alter table I18NText drop foreign key FKrisdlmalotmk64mdeqpo4s5m0;
alter table I18NText drop foreign key FKqxgws3fnukyqlaet11tivqg5u;
alter table I18NText drop foreign key FKthf8ix3t3opf9hya1s04hwsx8;
alter table I18NText drop foreign key FKg2jsybeuc8pbj8ek8xwxutuyo;
alter table I18NText drop foreign key FKp0m7uhipskrljktvfeubdgfid;
alter table I18NText drop foreign key FK6k8hmfvhko069970eghiy2ifp;
alter table I18NText drop foreign key FK8wn7sw34q6bifsi1pvl2b1yyb;
alter table Notification drop foreign key FKoxq5uqfg4ylwyijsg2ubyflna;
alter table Notification_BAs drop foreign key FK378pb1cvjv54w4ljqpw99s3wr;
alter table Notification_BAs drop foreign key FKb123fgeomc741s9yc014421yy;
alter table Notification_email_header drop foreign key FKd74pdu41avy2f7a8qyp7wn2n;
alter table Notification_email_header drop foreign key FKfdnoyp8rl0kxu29l4pyaa5566;
alter table Notification_Recipients drop foreign key FKot769nimyq1jvw0m61pgsq5g3;
alter table Notification_Recipients drop foreign key FKn7v944d0hw37bh0auv4gr3hsf;
alter table PeopleAssignments_BAs drop foreign key FKa90cdfgc4km384n1ataqigq67;
alter table PeopleAssignments_BAs drop foreign key FKt4xs0glwhbsa0xwg69r6xduv9;
alter table PeopleAssignments_ExclOwners drop foreign key FK5ituvd6t8uvp63hsx6282xo6h;
alter table PeopleAssignments_ExclOwners drop foreign key FKqxbjm1b3dl7w8w2f2y6sk0fv8;
alter table PeopleAssignments_PotOwners drop foreign key FKsa3rrrjsm1qw98ajbbu2s7cjr;
alter table PeopleAssignments_PotOwners drop foreign key FKh8oqmk4iuh2pmpgby6g8r3jd1;
alter table PeopleAssignments_Recipients drop foreign key FKrd0h9ud1bhs9waf2mdmiv6j2r;
alter table PeopleAssignments_Recipients drop foreign key FK9gnbv6bplxkxoedj35vg8n7ir;
alter table PeopleAssignments_Stakeholders drop foreign key FK9uy76cu650rg1nnkrtjwj1e9t;
alter table PeopleAssignments_Stakeholders drop foreign key FKaeyk4nwslvx0jywjomjq7083i;
alter table Reassignment drop foreign key FKessy30safh44b30f1cfoujv2k;
alter table Reassignment_potentialOwners drop foreign key FKsqrmpvehlc4qe9i0km22nmkjl;
alter table Reassignment_potentialOwners drop foreign key FKftegfexshix752bh2jfxf6bnh;
alter table Task drop foreign key FK48d1bfgwf0jqow1yk8ku4xcpi;
alter table Task drop foreign key FKpmkxvqq63aed2y2boruu53a0s;
alter table Task drop foreign key FKexuboqnbla7jfyyesyo61ucmb;
alter table task_comment drop foreign key FKqb4mkarf209y9546w7n75lb7a;
alter table task_comment drop foreign key FKm2mwc1ukcpdsiqwgkoroy6ise;
drop table if exists Attachment;
drop table if exists AuditTaskImpl;
drop table if exists BAMTaskSummary;
drop table if exists BooleanExpression;
drop table if exists CaseFileDataLog;
drop table if exists CaseIdInfo;
drop table if exists CaseRoleAssignmentLog;
drop table if exists Content;
drop table if exists ContextMappingInfo;
drop table if exists CorrelationKeyInfo;
drop table if exists CorrelationPropertyInfo;
drop table if exists Deadline;
drop table if exists Delegation_delegates;
drop table if exists DeploymentStore;
drop table if exists email_header;
drop table if exists ErrorInfo;
drop table if exists Escalation;
drop table if exists EventTypes;
drop table if exists ExecutionErrorInfo;
drop table if exists I18NText;
drop table if exists NodeInstanceLog;
drop table if exists Notification;
drop table if exists Notification_BAs;
drop table if exists Notification_email_header;
drop table if exists Notification_Recipients;
drop table if exists OrganizationalEntity;
drop table if exists PeopleAssignments_BAs;
drop table if exists PeopleAssignments_ExclOwners;
drop table if exists PeopleAssignments_PotOwners;
drop table if exists PeopleAssignments_Recipients;
drop table if exists PeopleAssignments_Stakeholders;
drop table if exists ProcessInstanceInfo;
drop table if exists ProcessInstanceLog;
drop table if exists QueryDefinitionStore;
drop table if exists Reassignment;
drop table if exists Reassignment_potentialOwners;
drop table if exists RequestInfo;
drop table if exists SessionInfo;
drop table if exists Task;
drop table if exists task_comment;
drop table if exists TaskDef;
drop table if exists TaskEvent;
drop table if exists TaskVariableImpl;
drop table if exists VariableInstanceLog;
drop table if exists WorkItemInfo;
